### ISSUE TITLE
upload_diagnostics not working

### ISSUE THREAD

**Issue by ashkan-leo** [numerai/numerapi#67] opened 2021-12-30 06:40 UTC
I am trying to get diagnostics. This is a code snippet I am using:
```python
publicid = ...
secretkey = ...
api = NumerAPI(publicid, secretkey)

submission_path = ...
model_id = ...
api.upload_diagnostics(submission_path, model_id=model_id)
```

I am getting the following error:
```python
2021-12-30 00:35:19,570 INFO numerapi.base_api: uploading diagnostics...
+2021-12-30 00:36:20,845 ERROR numerapi.utils: Http Error: 504 Server Error: Gateway Time-out for url: https://api-tournament.numer.ai/
2021-12-30 00:36:20,845 ERROR numerapi.utils: Did not receive a valid JSON: Expecting value: line 1 column 1 (char 0)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-d72ad6279651> in <module>
----> 1 api.upload_diagnostics("...", model_id="...")

/nix/store/3cb4vw75i6ranmzqwznaazhdf4wihzxq-python3-3.9.6-env/lib/python3.9/site-packages/numerapi/base_api.py in upload_diagnostics(self, file_path, tournament, model_id, df)
    448                      'modelId': model_id}
    449         create = self.raw_query(create_query, arguments, authorization=True)
--> 450         self.diagnostics_id = create['data']['createDiagnostics']['id']
    451         return self.diagnostics_id
    452

KeyError: 'data'
```

Is this because of the timeout error? If so, is there a way to increase the timeout?

**Comment by uuazed** [comment] 2022-01-14 12:05
Yes, that is related to that timeout, which seems to be happening on numerai's side. I wasn't able to reproduce this, unfortunately.

Could you please try again? I am closing this ticket, please re-open if it happens again.

**Closed as completed by uuazed** 2022-01-14 12:05 UTC
