### ISSUE TITLE
tqdm exceptions

### ISSUE THREAD

**Issue by kumikoda** [numerai/numerapi#12] opened 2019-01-22 20:56 UTC
Not sure what is going on here. Why would TQDM throw this exception? I don't believe tqdm is even invoked during the submission flow, so the exception must be from downloading the file, which already hit 100%??? 

Probably tqdm's fault: https://github.com/tqdm/tqdm/issues/613
```
/tmp/numerai_dataset_143.zip: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 160M/161M [00:24<00:00, 6.82MB/s]2019-01-19 10:00:27,212 INFO numerapi.numerapi: unzipping file...
2019-01-19 10:00:30,052 INFO numerapi.numerapi: uploading predictions...
/tmp/numerai_dataset_143.zip: 161MB [00:40, 6.82MB/s]                                                                                                                                                           2019-01-19 10:00:58,339 INFO numerapi.numerapi: uploading predictions...
2019-01-19 10:01:23,726 INFO numerapi.numerapi: uploading predictions...
2019-01-19 10:01:55,983 INFO numerapi.numerapi: uploading predictions...
2019-01-19 10:02:25,782 INFO numerapi.numerapi: uploading predictions...
2019-01-19 10:02:52,202 INFO numerapi.numerapi: uploading predictions...
2019-01-19 10:03:17,700 INFO numerapi.numerapi: uploading predictions...
Exception ignored in: <function tqdm.__del__ at 0x106b53950>
Traceback (most recent call last):
  File "/Users/anson/numerai/database-scripts/env/lib/python3.7/site-packages/tqdm-4.28.1-py3.7.egg/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/Users/anson/numerai/database-scripts/env/lib/python3.7/site-packages/tqdm-4.28.1-py3.7.egg/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/Users/anson/numerai/database-scripts/env/lib/python3.7/site-packages/tqdm-4.28.1-py3.7.egg/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/Users/anson/numerai/database-scripts/env/lib/python3.7/site-packages/tqdm-4.28.1-py3.7.egg/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by uuazed** [comment] 2019-01-24 08:54
I cannot reproduce this error. However, I remember seeing that at some point. I've increased the required tqdm version, hoping that this fixes it. Could also be related to Python3.7 (using 3.6 here). Could you provide a code snippet that produces the exception?

**Comment by uuazed** [comment] 2019-02-10 11:56
closing as not reproducible

**Closed as completed by uuazed** 2019-02-10 11:56 UTC
